name: Android Build APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11

      - name: Grant execute permission
        run: chmod +x ./gradlew

      # 🛠️ ส่วนสำคัญ: แก้ไขชื่อแอปและย้ายโฟลเดอร์อัตโนมัติ
      - name: Customize App and Package
        run: |
          if [ -f app_name.txt ]; then
            APP_NAME=$(cat app_name.txt)
            sed -i "s|<string name=\"app_name\">.*</string>|<string name=\"app_name\">$APP_NAME</string>|g" app/src/main/res/values/strings.xml
          fi
          
          if [ -f package.txt ]; then
            NEW_PKG=$(cat package.txt)
            sed -i "s/applicationId \".*\"/applicationId \"$NEW_PKG\"/" app/build.gradle
            sed -i "s/package=\".*\"/package=\"$NEW_PKG\"/" app/src/main/AndroidManifest.xml
            
            # ย้ายโฟลเดอร์ Java เพื่อแก้ปัญหา "แพ็กเกจไม่ถูกต้อง"
            NEW_PATH=$(echo $NEW_PKG | tr '.' '/')
            mkdir -p app/src/main/java/$NEW_PATH
            find app/src/main/java -name "*.java" -exec sed -i "s/package .*;/package $NEW_PKG;/" {} +
            find app/src/main/java -name "*.java" -type f -exec mv {} app/src/main/java/$NEW_PATH/ \;
          fi

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Publish to Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          name: Latest Cloud Build
          files: app/build/outputs/apk/release/*.apk
          force_update: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
